name: Lint

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: services/order-service/go.mod
          cache: false

      - name: Check formatting
        working-directory: services/order-service
        shell: bash
        run: |
          unformatted="$(gofmt -l .)"

          if [ -n "$unformatted" ]; then
            echo "These files are not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Vet
        working-directory: services/order-service
        run: go vet ./...
